export interface TopologyFamilyMetadata {
    label: string;
    pickerGroup: string;
    pickerOrder: number;
    family: string;
    sizingMode: string;
    viewportSyncMode: string;
}

export const TOPOLOGY_FAMILY_METADATA = Object.freeze({
    "square": {
        label: "Square",
        pickerGroup: "Classic",
        pickerOrder: 10,
        family: "regular",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "hex": {
        label: "Hexagonal",
        pickerGroup: "Classic",
        pickerOrder: 20,
        family: "regular",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "triangle": {
        label: "Triangular",
        pickerGroup: "Classic",
        pickerOrder: 30,
        family: "regular",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-4-8-8": {
        label: "Square-Octagon (4.8.8)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 110,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "trihexagonal-3-6-3-6": {
        label: "Kagome / Trihexagonal (3.6.3.6)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 120,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-3-12-12": {
        label: "Truncated Hexagonal (3.12.12)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 130,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-3-4-6-4": {
        label: "Rhombitrihexagonal (3.4.6.4)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 140,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-4-6-12": {
        label: "Truncated Trihexagonal (4.6.12)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 150,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-3-3-4-3-4": {
        label: "Snub Square (3.3.4.3.4)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 160,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-3-3-3-4-4": {
        label: "Elongated Triangular (3.3.3.4.4)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 170,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "archimedean-3-3-3-3-6": {
        label: "Snub Trihexagonal (3.3.3.3.6)",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 180,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "cairo-pentagonal": {
        label: "Cairo Pentagonal",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 190,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "rhombille": {
        label: "Rhombille",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 200,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "deltoidal-trihexagonal": {
        label: "Deltoidal Trihexagonal",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 210,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "deltoidal-hexagonal": {
        label: "Deltoidal Hexagonal",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 215,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "snub-square-dual": {
        label: "Snub Square Dual",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 220,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "penrose-p2-kite-dart": {
        label: "Penrose P2 Kite-Dart",
        pickerGroup: "Aperiodic",
        pickerOrder: 210,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "penrose-p3-rhombs": {
        label: "Penrose P3 Rhombs",
        pickerGroup: "Aperiodic",
        pickerOrder: 220,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "ammann-beenker": {
        label: "Ammann-Beenker",
        pickerGroup: "Aperiodic",
        pickerOrder: 230,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "tetrakis-square": {
        label: "Tetrakis Square",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 230,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "spectre": {
        label: "Spectre",
        pickerGroup: "Aperiodic",
        pickerOrder: 240,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "triakis-triangular": {
        label: "Triakis Triangular",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 240,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "hat-monotile": {
        label: "Hat",
        pickerGroup: "Aperiodic",
        pickerOrder: 250,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "prismatic-pentagonal": {
        label: "Prismatic Pentagonal",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 250,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "chair": {
        label: "Chair",
        pickerGroup: "Aperiodic",
        pickerOrder: 290,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "floret-pentagonal": {
        label: "Floret Pentagonal",
        pickerGroup: "Periodic Mixed",
        pickerOrder: 260,
        family: "mixed",
        sizingMode: "grid",
        viewportSyncMode: "backend-sync",
    },
    "taylor-socolar": {
        label: "Taylor-Socolar",
        pickerGroup: "Aperiodic",
        pickerOrder: 270,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "sphinx": {
        label: "Sphinx",
        pickerGroup: "Aperiodic",
        pickerOrder: 280,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "robinson-triangles": {
        label: "Robinson Triangles",
        pickerGroup: "Aperiodic",
        pickerOrder: 300,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "tuebingen-triangle": {
        label: "Tuebingen Triangle",
        pickerGroup: "Aperiodic",
        pickerOrder: 310,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "dodecagonal-square-triangle": {
        label: "Dodecagonal Square-Triangle",
        pickerGroup: "Experimental",
        pickerOrder: 320,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "shield": {
        label: "Shield",
        pickerGroup: "Experimental",
        pickerOrder: 330,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
    "pinwheel": {
        label: "Pinwheel",
        pickerGroup: "Experimental",
        pickerOrder: 340,
        family: "aperiodic",
        sizingMode: "patch_depth",
        viewportSyncMode: "presentation-only",
    },
} satisfies Readonly<Record<string, TopologyFamilyMetadata>>);

export function getTopologyFamilyMetadata(tilingFamily: string): TopologyFamilyMetadata | null {
    return (TOPOLOGY_FAMILY_METADATA as Readonly<Record<string, TopologyFamilyMetadata>>)[tilingFamily] ?? null;
}
