[mypy]
python_version = 3.13
files = app.py, backend, tests, tools
explicit_package_bases = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_reexport = True

[mypy-backend.*]
check_untyped_defs = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-tools.*]
check_untyped_defs = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-tests.api.*]
check_untyped_defs = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-tests.e2e.support_server]
check_untyped_defs = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-tests.e2e.support_browser]
check_untyped_defs = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-tests.e2e.browser_support.*]
check_untyped_defs = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-shapely.*]
ignore_missing_imports = True

[mypy-playwright.*]
ignore_missing_imports = True
