export const SHIELD_RENDER_COORDINATE_SCALE = 0.35;

export const APERIODIC_RENDER_SCALE_MULTIPLIER = 10;
export const APERIODIC_MIN_METRIC_CELL_SIZE = 0.25;
export const APERIODIC_MIN_CENTER_CELL_SIZE = 6;

export const CHAIR_RENDER_MARGIN_MIN = 8;
export const CHAIR_RENDER_MARGIN_SCALE = 0.15;
export const SHIELD_RENDER_MARGIN_MIN = 10;
export const SHIELD_RENDER_MARGIN_SCALE = 0.18;
export const DEFAULT_APERIODIC_RENDER_MARGIN_MIN = 16;
export const DEFAULT_APERIODIC_RENDER_MARGIN_SCALE = 0.45;
