import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
    decodeCellMutationDelta,
    decodeInitResponse,
    decodeRequestResponse,
    decodeTickResponse,
} from "./runtime-decoders.js";

/**
 * Contract test against verbatim standalone-runtime responses generated by
 * `python -m tools fixtures decoder-contract`. Guards both drift directions:
 * a decoder that rejects a genuine backend payload throws here, and a decoder
 * that silently drops a payload field fails the round-trip equality below.
 */

const testDir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(testDir, "../test-fixtures/decoder-contract/worker-responses.json");

interface FixtureEntry {
    decoder: "init" | "request" | "tick" | "delta";
    response: Record<string, unknown>;
}

const fixtureDocument = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as {
    responses: Record<string, FixtureEntry>;
};
const entries = Object.entries(fixtureDocument.responses);

const EXPECTED_ENTRIES = [
    "control-reset",
    "init",
    "state",
    "rules",
    "cells-set-many",
    "http-cell-delta",
    "control-step",
    "tick-idle",
    "tick-running",
    "compare",
    "filmstrip",
    "topology-preview-square",
    "topology-preview-cairo",
    "error-topology-budget",
    "error-unknown-command",
];

const TOP_LEVEL_RENAMES: Readonly<Record<string, string>> = {
    persisted_snapshot: "persistedSnapshot",
    topology_preview: "topologyPreview",
};

const CELL_DELTA_KEYS = new Set([
    "base_state_revision",
    "state_revision",
    "state_epoch",
    "topology_revision",
    "generation",
    "cell_updates",
]);

function requireEntry(name: string): FixtureEntry {
    const entry = fixtureDocument.responses[name];
    if (!entry) {
        throw new Error(`Fixture entry ${name} is missing; regenerate the contract fixture.`);
    }
    return entry;
}

function decodeEntry(entry: FixtureEntry): unknown {
    const raw = JSON.stringify(entry.response);
    switch (entry.decoder) {
        case "init":
            return decodeInitResponse(raw);
        case "request":
            return decodeRequestResponse(raw);
        case "tick":
            return decodeTickResponse(raw);
        case "delta":
            return decodeCellMutationDelta(entry.response);
    }
}

function expectedDecodedEntry(entry: FixtureEntry): Record<string, unknown> {
    if (entry.decoder === "delta") {
        return entry.response;
    }

    const expected: Record<string, unknown> = {};
    const cellDelta: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(entry.response)) {
        // Init success is represented by the decoder returning its data;
        // unlike command responses, its public contract has no `ok` field.
        if (entry.decoder === "init" && key === "ok") {
            continue;
        }
        if (entry.decoder === "request" && CELL_DELTA_KEYS.has(key)) {
            cellDelta[key] = value;
            continue;
        }
        expected[TOP_LEVEL_RENAMES[key] ?? key] = value;
    }
    if (Object.keys(cellDelta).length > 0) {
        expected.cellDelta = cellDelta;
    }
    if (entry.decoder === "init" && expected.persistedSnapshot === undefined) {
        expected.persistedSnapshot = null;
    }
    return expected;
}

describe("runtime decoder contract fixtures", () => {
    it("covers the expected runtime responses", () => {
        expect(Object.keys(fixtureDocument.responses).sort()).toEqual([...EXPECTED_ENTRIES].sort());
    });

    it.each(entries)("decodes the %s response without loss", (_name, entry) => {
        const decoded = decodeEntry(entry) as Record<string, unknown>;

        // Compare the complete envelope after the explicit public adapters
        // above. Any new backend field must therefore survive decoding or be
        // added as an intentional adapter here.
        expect(decoded).toEqual(expectedDecodedEntry(entry));
    });

    it("preserves structured error details", () => {
        const decoded = decodeEntry(requireEntry("error-topology-budget")) as Record<
            string,
            unknown
        >;
        expect(decoded.ok).toBe(false);
        expect(decoded.code).toBe("topology_cell_budget_exceeded");
        expect(typeof decoded.error).toBe("string");
        expect(typeof decoded.limit).toBe("number");
        expect(typeof decoded.estimated_cells).toBe("number");

        const unknownCommand = decodeEntry(requireEntry("error-unknown-command")) as Record<
            string,
            unknown
        >;
        expect(unknownCommand.ok).toBe(false);
        expect(unknownCommand.error).toContain("Unknown command");
    });

    it("reports tick progression", () => {
        const idle = decodeEntry(requireEntry("tick-idle")) as Record<string, unknown>;
        expect(idle).toEqual({ ok: true, stepped: false });

        const running = decodeEntry(requireEntry("tick-running")) as Record<string, unknown>;
        expect(running.stepped).toBe(true);
        expect(running.snapshot).toBeDefined();
    });
});
