import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
    decodeCellMutationDelta,
    decodeInitResponse,
    decodeRequestResponse,
    decodeTickResponse,
} from "./runtime-decoders.js";

/**
 * Contract test against verbatim standalone-runtime responses generated by
 * `python -m tools fixtures decoder-contract`. Guards both drift directions:
 * a decoder that rejects a genuine backend payload throws here, and a decoder
 * that silently drops a payload field fails the round-trip equality below.
 */

const testDir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(testDir, "../test-fixtures/decoder-contract/worker-responses.json");

interface FixtureEntry {
    decoder: "init" | "request" | "tick" | "delta";
    response: Record<string, unknown>;
}

const fixtureDocument = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as {
    responses: Record<string, FixtureEntry>;
};
const entries = Object.entries(fixtureDocument.responses);

const EXPECTED_ENTRIES = [
    "control-reset",
    "init",
    "state",
    "rules",
    "cells-set-many",
    "http-cell-delta",
    "control-step",
    "tick-idle",
    "tick-running",
    "compare",
    "filmstrip",
    "topology-preview-square",
    "topology-preview-cairo",
    "error-topology-budget",
    "error-unknown-command",
];

function requireEntry(name: string): FixtureEntry {
    const entry = fixtureDocument.responses[name];
    if (!entry) {
        throw new Error(`Fixture entry ${name} is missing; regenerate the contract fixture.`);
    }
    return entry;
}

function decodeEntry(entry: FixtureEntry): unknown {
    const raw = JSON.stringify(entry.response);
    switch (entry.decoder) {
        case "init":
            return decodeInitResponse(raw);
        case "request":
            return decodeRequestResponse(raw);
        case "tick":
            return decodeTickResponse(raw);
        case "delta":
            return decodeCellMutationDelta(entry.response);
    }
}

describe("runtime decoder contract fixtures", () => {
    it("covers the expected runtime responses", () => {
        expect(Object.keys(fixtureDocument.responses).sort()).toEqual([...EXPECTED_ENTRIES].sort());
    });

    it.each(entries)("decodes the %s response without loss", (name, entry) => {
        const decoded = decodeEntry(entry) as Record<string, unknown>;
        const response = entry.response;

        if (entry.decoder === "delta") {
            expect(decoded).toEqual(response);
            return;
        }
        // Shared payload sections must survive decoding byte-for-byte; a field
        // added on the backend but not copied by a decoder fails here.
        if (response.snapshot !== undefined) {
            expect(decoded.snapshot).toEqual(response.snapshot);
        }
        if (response.persisted_snapshot !== undefined) {
            expect(decoded.persistedSnapshot).toEqual(response.persisted_snapshot);
        }
        if (entry.decoder !== "init") {
            expect(decoded.ok).toBe(response.ok);
        }
        if (response.rules !== undefined) {
            expect(decoded.rules).toEqual(response.rules);
        }
        if (response.comparison !== undefined) {
            expect(decoded.comparison).toEqual(response.comparison);
        }
        if (response.filmstrip !== undefined) {
            expect(decoded.filmstrip).toEqual(response.filmstrip);
        }
        if (response.topology_preview !== undefined) {
            expect(decoded.topologyPreview).toEqual(response.topology_preview);
        }
        if (response.base_state_revision !== undefined) {
            const { ok: _ok, ...deltaPayload } = response;
            expect(decoded.cellDelta).toEqual(deltaPayload);
        }
    });

    it("preserves structured error details", () => {
        const decoded = decodeEntry(requireEntry("error-topology-budget")) as Record<
            string,
            unknown
        >;
        expect(decoded.ok).toBe(false);
        expect(decoded.code).toBe("topology_cell_budget_exceeded");
        expect(typeof decoded.error).toBe("string");
        expect(typeof decoded.limit).toBe("number");
        expect(typeof decoded.estimated_cells).toBe("number");

        const unknownCommand = decodeEntry(requireEntry("error-unknown-command")) as Record<
            string,
            unknown
        >;
        expect(unknownCommand.ok).toBe(false);
        expect(unknownCommand.error).toContain("Unknown command");
    });

    it("reports tick progression", () => {
        const idle = decodeEntry(requireEntry("tick-idle")) as Record<string, unknown>;
        expect(idle).toEqual({ ok: true, stepped: false });

        const running = decodeEntry(requireEntry("tick-running")) as Record<string, unknown>;
        expect(running.stepped).toBe(true);
        expect(running.snapshot).toBeDefined();
    });
});
