from __future__ import annotations

from backend.simulation.aperiodic_family_manifest import (
    TAYLOR_HALF_HEX_KIND,
    TAYLOR_SOCOLAR_GEOMETRY,
)
from backend.simulation.reference_specs.types import (
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

from ._helpers import _public_cell_kinds, _reference_label

SPECS = {
    TAYLOR_SOCOLAR_GEOMETRY: ReferenceFamilySpec(
        geometry=TAYLOR_SOCOLAR_GEOMETRY,
        display_name=_reference_label(TAYLOR_SOCOLAR_GEOMETRY),
        source_urls=("https://tilings.math.uni-bielefeld.de/substitution/half-hex/",),
        canonical_root_seed_policy="paired half-hex seed",
        allowed_public_cell_kinds=_public_cell_kinds(TAYLOR_SOCOLAR_GEOMETRY),
        required_metadata=(),
        depth_expectations={
            0: ReferenceDepthExpectation(
                exact_total_cells=2,
                required_kinds=(TAYLOR_HALF_HEX_KIND,),
                required_adjacency_pairs=((TAYLOR_HALF_HEX_KIND, TAYLOR_HALF_HEX_KIND),),
            ),
            1: ReferenceDepthExpectation(exact_total_cells=8),
            2: ReferenceDepthExpectation(exact_total_cells=32),
            3: ReferenceDepthExpectation(
                exact_total_cells=128,
                canonical_patch_fixture_key="exact-depth-3",
            ),
        },
        notes=(
            "Generated by the 1-into-4 half-hex substitution from the "
            "Bielefeld Tilings Encyclopedia "
            "(https://tilings.math.uni-bielefeld.de/substitution/half-hex/), "
            "attributed there to Gruenbaum & Shephard 1987 / Frettloeh 2002. "
            "Each prototile is an isosceles trapezoid forming half of a regular "
            "hexagon; pairs of half-hexes assemble into the regular hexagons that "
            "the published Socolar-Taylor monotile (Socolar & Taylor 2011, "
            "arXiv:1009.1419) decorates with R1 stripes + R2 flags + chirality "
            "coloring to force aperiodicity. This implementation generates the "
            "underlying half-hex hierarchy and stamps substitution-tree "
            "decoration tokens (hex-half:upper/lower at the root, "
            "substitution-role:in-place/paired/outer-left/outer-right at each "
            "child) so a future renderer can attach the canonical decorations, "
            "but the R1/R2 markings and chirality coloring themselves are not "
            "computed or rendered. Without those decorations the bare half-hex "
            "substitution does not by itself demonstrate Taylor-Socolar "
            "aperiodicity. See docs/TILING_KNOWN_DEVIATIONS.md for the gap.",
        ),
    ),
}
