from __future__ import annotations

from backend.simulation.aperiodic_family_manifest import (
    TAYLOR_HALF_HEX_LEFT_KIND,
    TAYLOR_HALF_HEX_RIGHT_KIND,
    TAYLOR_SOCOLAR_GEOMETRY,
)
from backend.simulation.reference_specs.types import (
    MetadataRequirement,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

from ._helpers import _public_cell_kinds, _reference_label

SPECS = {
    TAYLOR_SOCOLAR_GEOMETRY: ReferenceFamilySpec(
        geometry=TAYLOR_SOCOLAR_GEOMETRY,
        display_name=_reference_label(TAYLOR_SOCOLAR_GEOMETRY),
        source_urls=(
            "https://tilings.math.uni-bielefeld.de/substitution/half-hex/",
            "https://arxiv.org/abs/1009.1419",
            "https://arxiv.org/abs/1210.3967",
        ),
        canonical_root_seed_policy=(
            "paired half-hex seed (one upper + one lower; both share chirality 'left' "
            "so the central pair forms one full chiral hexagon)"
        ),
        allowed_public_cell_kinds=_public_cell_kinds(TAYLOR_SOCOLAR_GEOMETRY),
        required_metadata=(
            MetadataRequirement(
                kind=TAYLOR_HALF_HEX_LEFT_KIND,
                fields=("chirality_token", "orientation_token"),
            ),
            MetadataRequirement(
                kind=TAYLOR_HALF_HEX_RIGHT_KIND,
                fields=("chirality_token", "orientation_token"),
            ),
        ),
        depth_expectations={
            0: ReferenceDepthExpectation(
                exact_total_cells=2,
                # Both roots share chirality 'left' (they're the two halves of
                # the same central hex), so depth-0 contains only 'left' cells.
                expected_kind_counts=((TAYLOR_HALF_HEX_LEFT_KIND, 2),),
                required_kinds=(TAYLOR_HALF_HEX_LEFT_KIND,),
                required_adjacency_pairs=((TAYLOR_HALF_HEX_LEFT_KIND, TAYLOR_HALF_HEX_LEFT_KIND),),
            ),
            1: ReferenceDepthExpectation(
                exact_total_cells=8,
                # 1 of the 4 substitution children ('paired') flips chirality;
                # the other 3 inherit. From 2 left roots: 6 left + 2 right.
                expected_kind_counts=(
                    (TAYLOR_HALF_HEX_LEFT_KIND, 6),
                    (TAYLOR_HALF_HEX_RIGHT_KIND, 2),
                ),
            ),
            2: ReferenceDepthExpectation(
                # From 6L: 18L + 6R; from 2R: 2L + 6R. Total: 20L + 12R.
                exact_total_cells=32,
                expected_kind_counts=(
                    (TAYLOR_HALF_HEX_LEFT_KIND, 20),
                    (TAYLOR_HALF_HEX_RIGHT_KIND, 12),
                ),
            ),
            3: ReferenceDepthExpectation(
                # From 20L: 60L + 20R; from 12R: 12L + 36R. Total: 72L + 56R.
                exact_total_cells=128,
                expected_kind_counts=(
                    (TAYLOR_HALF_HEX_LEFT_KIND, 72),
                    (TAYLOR_HALF_HEX_RIGHT_KIND, 56),
                ),
                canonical_patch_fixture_key="exact-depth-3",
            ),
        },
        notes=(
            "Generated by the 1-into-4 half-hex substitution from the Bielefeld "
            "Tilings Encyclopedia "
            "(https://tilings.math.uni-bielefeld.de/substitution/half-hex/), "
            "attributed there to Gruenbaum & Shephard 1987 / Frettloeh 2002. "
            "Per Baake-Gaehler-Grimm 2012 (arXiv:1210.3967), this is the bare "
            "geometric substitution that the Socolar-Taylor 14-prototile "
            "substitution (Socolar & Taylor 2011, arXiv:1009.1419, Fig. 9; "
            "Baake-Gaehler-Grimm Fig. 7) layers chirality + 7-colour labels on "
            "top of. This implementation carries the chirality bit by flipping "
            "chirality on the one substitution child that is geometrically "
            "reflected (the 'paired' child, rotated by pi); the other three "
            "children inherit the parent's chirality. Both roots seed with "
            "chirality 'left', so the central pair forms one full chiral "
            "hexagon and the depth-d L/R split balances toward 50/50 as the "
            "substitution iterates (2/0, 6/2, 20/12, 72/56 at depths 0..3). "
            "Cells are emitted as two distinct kinds (taylor-half-hex-left, "
            "taylor-half-hex-right) so palette, renderer, and CA rules can "
            "distinguish them. The 7-colour A-G labelling that determines the "
            "exact R1 stripe and R2 flag positions per hex in the full Taylor "
            "tiling is NOT computed; see docs/TILING_KNOWN_DEVIATIONS.md for "
            "what closing that gap would require.",
        ),
    ),
}
