from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Pythagorean tiling: two square prototiles in a 1:2 size ratio, tiled in
# the classic "broken brick" / pinwheel-of-squares pattern. The translation
# lattice is generated by u=(a, b), v=(-b, a) where a, b are the square
# sides; with a=2, b=1 the smallest axis-aligned fundamental domain is a
# 5x5 cell containing 5 large + 5 small squares.
#
# The tiling is non-edge-to-edge: every large-square edge is bisected at
# its midpoint by an incident small-square corner (T-junction). To make
# adjacency by exact edge matching work, large squares are modelled as
# 8-vertex polygons (4 corners + 4 collinear mid-edge vertices), so every
# polygon edge ends at a vertex shared with the neighboring face.
#
# All vertices in the infinite tiling have the same configuration:
# 3 faces meet (two large squares + one small square).

SPECS = {
    "pythagorean": ReferenceFamilySpec(
        geometry="pythagorean",
        display_name="Pythagorean",
        source_urls=("https://en.wikipedia.org/wiki/Pythagorean_tiling",),
        canonical_root_seed_policy="descriptor-driven open-boundary 3x3 sample",
        allowed_public_cell_kinds=("pythagorean-large", "pythagorean-small"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            3: ReferenceDepthExpectation(
                exact_total_cells=96,
                expected_kind_counts=(
                    ("pythagorean-large", 51),
                    ("pythagorean-small", 45),
                ),
                expected_adjacency_pairs=(
                    ("pythagorean-large", "pythagorean-large"),
                    ("pythagorean-large", "pythagorean-small"),
                ),
                expected_degree_histogram=(
                    (2, 1),
                    (3, 12),
                    (4, 45),
                    (6, 9),
                    (8, 29),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=10,
            slot_vocabulary=("b0", "b1", "b2", "b3", "b4", "s0", "s1", "s2", "s3", "s4"),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                (
                    "pythagorean-large",
                    "pythagorean-large",
                    "pythagorean-small",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                # Every vertex in the Pythagorean tiling is a T-junction
                # where one small-square corner meets the midpoint of one
                # big-square edge plus the corner of an adjacent big
                # square (large, large, small). In the open-boundary 3x3
                # sample the verifier counts 157 such interior vertices.
                (
                    (
                        "pythagorean-large",
                        "pythagorean-large",
                        "pythagorean-small",
                    ),
                    157,
                ),
            ),
        ),
    ),
}
