from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-2-3122-34312 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-2-3122-34312": ReferenceFamilySpec(
        geometry="uniform-2-2-3122-34312",
        display_name="2-uniform #2 (3.12^2; 3.4.3.12)",
        source_urls=("https://commons.wikimedia.org/wiki/File:2-uniform_n2.svg",),
        canonical_root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("dodecagon", "square", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=105,
                expected_kind_counts=(
                    ("dodecagon", 25),
                    ("square", 16),
                    ("triangle", 64),
                ),
                expected_adjacency_pairs=(
                    ("dodecagon", "dodecagon"),
                    ("dodecagon", "triangle"),
                    ("square", "triangle"),
                ),
                expected_degree_histogram=(
                    (3, 64),
                    (4, 20),
                    (7, 12),
                    (12, 9),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=6,
            slot_vocabulary=(
                "dodecagon",
                "square",
                "triangle-bottom",
                "triangle-left",
                "triangle-right",
                "triangle-top",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                ("dodecagon", "dodecagon", "triangle"),
                ("dodecagon", "triangle", "square", "triangle"),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    ("dodecagon", "dodecagon", "triangle"),
                    64,
                ),
                (
                    ("dodecagon", "triangle", "square", "triangle"),
                    64,
                ),
            ),
        ),
    ),
}
