from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-16-v1-33344-33434 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-16-v1-33344-33434": ReferenceFamilySpec(
        geometry="uniform-2-16-v1-33344-33434",
        display_name="2-uniform #16 variant 1 (3^3.4^2; 3^2.4.3.4)",
        source_urls=("https://commons.wikimedia.org/wiki/File:2-uniform_n16.svg",),
        root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("square", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=604,
                expected_kind_counts=(
                    ("square", 204),
                    ("triangle", 400),
                ),
                expected_adjacency_pairs=(
                    ("square", "square"),
                    ("square", "triangle"),
                    ("triangle", "triangle"),
                ),
                expected_degree_histogram=(
                    (2, 42),
                    (3, 396),
                    (4, 166),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=36,
            slot_vocabulary=(
                "s24",
                "s25",
                "s26",
                "s27",
                "s28",
                "s29",
                "s30",
                "s31",
                "s32",
                "s33",
                "s34",
                "s35",
                "t00",
                "t01",
                "t02",
                "t03",
                "t04",
                "t05",
                "t06",
                "t07",
                "t08",
                "t09",
                "t10",
                "t11",
                "t12",
                "t13",
                "t14",
                "t15",
                "t16",
                "t17",
                "t18",
                "t19",
                "t20",
                "t21",
                "t22",
                "t23",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                (
                    "square",
                    "square",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
                (
                    "square",
                    "triangle",
                    "square",
                    "triangle",
                    "triangle",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    (
                        "square",
                        "square",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    117,
                ),
                (
                    (
                        "square",
                        "triangle",
                        "square",
                        "triangle",
                        "triangle",
                    ),
                    248,
                ),
            ),
        ),
    ),
}
