from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-7-v1-3426-3636 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-7-v1-3426-3636": ReferenceFamilySpec(
        geometry="uniform-2-7-v1-3426-3636",
        display_name="2-uniform #7 variant 1 (3.4^2.6; 3.6.3.6)",
        source_urls=("https://commons.wikimedia.org/wiki/File:2-uniform_n7.svg",),
        root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("hexagon", "square", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=706,
                expected_kind_counts=(
                    ("hexagon", 153),
                    ("square", 264),
                    ("triangle", 289),
                ),
                expected_adjacency_pairs=(
                    ("hexagon", "square"),
                    ("hexagon", "triangle"),
                    ("square", "square"),
                    ("square", "triangle"),
                ),
                expected_degree_histogram=(
                    (1, 2),
                    (2, 40),
                    (3, 288),
                    (4, 248),
                    (5, 16),
                    (6, 112),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=40,
            slot_vocabulary=(
                "h32",
                "h33",
                "h34",
                "h35",
                "h36",
                "h37",
                "h38",
                "h39",
                "s16",
                "s17",
                "s18",
                "s19",
                "s20",
                "s21",
                "s22",
                "s23",
                "s24",
                "s25",
                "s26",
                "s27",
                "s28",
                "s29",
                "s30",
                "s31",
                "t00",
                "t01",
                "t02",
                "t03",
                "t04",
                "t05",
                "t06",
                "t07",
                "t08",
                "t09",
                "t10",
                "t11",
                "t12",
                "t13",
                "t14",
                "t15",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                ("hexagon", "square", "square", "triangle"),
                ("hexagon", "triangle", "hexagon", "triangle"),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    ("hexagon", "square", "square", "triangle"),
                    512,
                ),
                (
                    ("hexagon", "triangle", "hexagon", "triangle"),
                    128,
                ),
            ),
        ),
    ),
}
