from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-4-v1-44-33344 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-4-v1-44-33344": ReferenceFamilySpec(
        geometry="uniform-2-4-v1-44-33344",
        display_name="2-uniform #4 variant 1 (4^4; 3^3.4^2)",
        source_urls=("https://commons.wikimedia.org/wiki/File:2-uniform_n4.svg",),
        root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("square", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=128,
                expected_kind_counts=(
                    ("square", 64),
                    ("triangle", 64),
                ),
                expected_adjacency_pairs=(
                    ("square", "square"),
                    ("square", "triangle"),
                    ("triangle", "triangle"),
                ),
                expected_degree_histogram=(
                    (2, 12),
                    (3, 80),
                    (4, 36),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=8,
            slot_vocabulary=("s04", "s05", "s06", "s07", "t00", "t01", "t02", "t03"),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                ("square", "square", "square", "square"),
                (
                    "square",
                    "square",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    ("square", "square", "square", "square"),
                    21,
                ),
                (
                    (
                        "square",
                        "square",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    56,
                ),
            ),
        ),
    ),
}
