from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-10-36-3262 at patch_size=3. Counts and
# vertex configuration frequencies reflect the open-boundary 3x3 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-10-36-3262": ReferenceFamilySpec(
        geometry="uniform-2-10-36-3262",
        display_name="2-uniform #10",
        source_urls=(
            "https://en.wikipedia.org/wiki/List_of_k-uniform_tilings",
            "https://commons.wikimedia.org/wiki/File:2-uniform_n10.svg",
        ),
        canonical_root_seed_policy="descriptor-driven open-boundary 3x3 sample",
        allowed_public_cell_kinds=("hexagon", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            3: ReferenceDepthExpectation(
                exact_total_cells=175,
                expected_kind_counts=(
                    ("hexagon", 46),
                    ("triangle", 129),
                ),
                expected_adjacency_pairs=(
                    ("hexagon", "hexagon"),
                    ("hexagon", "triangle"),
                    ("triangle", "triangle"),
                ),
                expected_degree_histogram=(
                    (2, 23),
                    (3, 112),
                    (4, 10),
                    (5, 2),
                    (6, 28),
                ),
                expected_signature="bf595c100c10",  # pragma: allowlist secret
                regular_polygon_kinds=("hexagon", "triangle"),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=16,
            slot_vocabulary=(
                "d11",
                "d12",
                "d14",
                "d15",
                "d21",
                "d24",
                "hex_a",
                "hex_b",
                "hex_c",
                "hex_d",
                "u12",
                "u15",
                "u21",
                "u22",
                "u24",
                "u25",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                ("hexagon", "hexagon", "triangle", "triangle"),
                (
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    ("hexagon", "hexagon", "triangle", "triangle"),
                    108,
                ),
                (
                    (
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    18,
                ),
            ),
        ),
    ),
}
