from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-19-v1-36-346 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-19-v1-36-346": ReferenceFamilySpec(
        geometry="uniform-2-19-v1-36-346",
        display_name="2-uniform #19 variant 1 (3^6; 3^4.6)",
        source_urls=("https://commons.wikimedia.org/wiki/File:2-uniform_n19.svg",),
        canonical_root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("hexagon", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=861,
                expected_kind_counts=(
                    ("hexagon", 77),
                    ("triangle", 784),
                ),
                expected_adjacency_pairs=(
                    ("hexagon", "triangle"),
                    ("triangle", "triangle"),
                ),
                expected_degree_histogram=(
                    (2, 52),
                    (3, 750),
                    (4, 6),
                    (6, 53),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=52,
            slot_vocabulary=(
                "d00",
                "d01",
                "d03",
                "d04",
                "d10",
                "d11",
                "d12",
                "d13",
                "d14",
                "d15",
                "d21",
                "d24",
                "d30",
                "d31",
                "d33",
                "d34",
                "d40",
                "d41",
                "d42",
                "d43",
                "d44",
                "d45",
                "d51",
                "d54",
                "hex-00",
                "hex-03",
                "hex-30",
                "hex-33",
                "u01",
                "u04",
                "u10",
                "u11",
                "u12",
                "u13",
                "u14",
                "u15",
                "u21",
                "u22",
                "u24",
                "u25",
                "u31",
                "u34",
                "u40",
                "u41",
                "u42",
                "u43",
                "u44",
                "u45",
                "u51",
                "u52",
                "u54",
                "u55",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                (
                    "hexagon",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
                (
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    (
                        "hexagon",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    368,
                ),
                (
                    (
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    120,
                ),
            ),
        ),
    ),
}
