from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-3-4-36-3262-63 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-3-4-36-3262-63": ReferenceFamilySpec(
        geometry="uniform-3-4-36-3262-63",
        display_name="3-uniform #4 (3^6; 3^2.6^2; 6^3)",
        source_urls=("https://commons.wikimedia.org/wiki/File:3-uniform_4.svg",),
        root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("hexagon", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=608,
                expected_kind_counts=(
                    ("hexagon", 208),
                    ("triangle", 400),
                ),
                expected_adjacency_pairs=(
                    ("hexagon", "hexagon"),
                    ("hexagon", "triangle"),
                    ("triangle", "triangle"),
                ),
                expected_degree_histogram=(
                    (2, 48),
                    (3, 377),
                    (4, 7),
                    (5, 7),
                    (6, 169),
                ),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=36,
            slot_vocabulary=(
                "h0-1",
                "h0-2",
                "h0-3",
                "h0-4",
                "h0-5",
                "h0-6",
                "h1-1",
                "h1-2",
                "h1-3",
                "h1-4",
                "h1-5",
                "h1-6",
                "t0-10",
                "t0-11",
                "t0-12",
                "t0-13",
                "t0-14",
                "t0-15",
                "t0-16",
                "t0-17",
                "t0-18",
                "t0-7",
                "t0-8",
                "t0-9",
                "t1-10",
                "t1-11",
                "t1-12",
                "t1-13",
                "t1-14",
                "t1-15",
                "t1-16",
                "t1-17",
                "t1-18",
                "t1-7",
                "t1-8",
                "t1-9",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                ("hexagon", "hexagon", "hexagon"),
                ("hexagon", "hexagon", "triangle", "triangle"),
                (
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    ("hexagon", "hexagon", "hexagon"),
                    128,
                ),
                (
                    ("hexagon", "hexagon", "triangle", "triangle"),
                    353,
                ),
                (
                    (
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    64,
                ),
            ),
        ),
    ),
}
