from __future__ import annotations

from backend.simulation.reference_specs.types import (
    PeriodicDescriptorExpectation,
    ReferenceDepthExpectation,
    ReferenceFamilySpec,
)

# Generated by tools/sketch_tiling.py from
# uniform-2-12-3262-346 at patch_size=4. Counts and
# vertex configuration frequencies reflect the open-boundary 4x4 sample
# the reference verifier itself runs.

SPECS = {
    "uniform-2-12-3262-346": ReferenceFamilySpec(
        geometry="uniform-2-12-3262-346",
        display_name="2-uniform #12 (3^2.6^2; 3^4.6)",
        source_urls=("https://commons.wikimedia.org/wiki/File:2-uniform_n12.svg",),
        canonical_root_seed_policy="descriptor-driven open-boundary 4x4 sample",
        allowed_public_cell_kinds=("hexagon", "triangle"),
        required_metadata=(),
        sample_mode="grid",
        depth_expectations={
            4: ReferenceDepthExpectation(
                exact_total_cells=348,
                expected_kind_counts=(
                    ("hexagon", 76),
                    ("triangle", 272),
                ),
                expected_adjacency_pairs=(
                    ("hexagon", "hexagon"),
                    ("hexagon", "triangle"),
                    ("triangle", "triangle"),
                ),
                expected_degree_histogram=(
                    (2, 24),
                    (3, 256),
                    (4, 12),
                    (5, 10),
                    (6, 46),
                ),
                expected_signature="d0eff300e2a7",  # pragma: allowlist secret
                regular_polygon_kinds=("hexagon", "triangle"),
            ),
        },
        periodic_descriptor=PeriodicDescriptorExpectation(
            face_template_count=20,
            slot_vocabulary=(
                "hex-1",
                "hex-2",
                "hex-shifted-1",
                "hex-shifted-2",
                "t1-1",
                "t1-2",
                "t2-1",
                "t2-2",
                "t3-1",
                "t3-2",
                "t4-1",
                "t4-2",
                "t5-1",
                "t5-2",
                "t6-1",
                "t6-2",
                "t7-1",
                "t7-2",
                "t8-1",
                "t8-2",
            ),
            id_pattern="{prefix}:{slot}:{x}:{y}",
            row_offset_x=0.0,
            expected_interior_vertex_configurations=(
                ("hexagon", "hexagon", "triangle", "triangle"),
                (
                    "hexagon",
                    "triangle",
                    "triangle",
                    "triangle",
                    "triangle",
                ),
            ),
            expected_interior_vertex_configuration_frequencies=(
                (
                    ("hexagon", "hexagon", "triangle", "triangle"),
                    120,
                ),
                (
                    (
                        "hexagon",
                        "triangle",
                        "triangle",
                        "triangle",
                        "triangle",
                    ),
                    128,
                ),
            ),
        ),
    ),
}
