from __future__ import annotations

# Generated by tools/export_dodecagonal_square_triangle_contract_generator.py.
# Do not edit by hand; regenerate from the checked-in backend generator contract.

import argparse
import json
import math
import sys
from collections import defaultdict
from functools import lru_cache
from pathlib import Path
from typing import TypedDict


REFERENCE_PATCH_PATH = Path(__file__).resolve().parent / "reference-patch.json"
PATCH_DISTANCE_THRESHOLDS = {
    0: 4,
    1: 16,
    2: 40,
    3: 76,
    4: 97,
}
EDGE_PRECISION = 6


class PatchCell(TypedDict):
    id: str
    kind: str
    center: tuple[float, float]
    vertices: tuple[tuple[float, float], ...]
    neighbors: tuple[str, ...]
    tile_family: str | None
    orientation_token: str | None
    chirality_token: str | None
    decoration_tokens: tuple[str, ...] | None


class AperiodicPatch(TypedDict):
    patch_depth: int
    width: int
    height: int
    cells: tuple[PatchCell, ...]


Point = tuple[float, float]
EdgeKey = tuple[Point, Point]


@lru_cache(maxsize=1)
def _load_reference_records() -> tuple[dict[str, object], ...]:
    with REFERENCE_PATCH_PATH.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    return tuple(payload["records"])


def _resolve_depth(patch_depth: int) -> int:
    return max(0, int(patch_depth))


def _resolve_threshold(resolved_depth: int) -> int:
    min_depth = min(PATCH_DISTANCE_THRESHOLDS)
    max_depth = max(PATCH_DISTANCE_THRESHOLDS)
    clamped_depth = min(max(resolved_depth, min_depth), max_depth)
    return PATCH_DISTANCE_THRESHOLDS[clamped_depth]


def _to_point(raw_point: list[float]) -> Point:
    return (float(raw_point[0]), float(raw_point[1]))


def _round_point(point: Point) -> Point:
    return (round(point[0], EDGE_PRECISION), round(point[1], EDGE_PRECISION))


def _canonicalize_edge(start: Point, end: Point) -> EdgeKey:
    rounded_start = _round_point(start)
    rounded_end = _round_point(end)
    if rounded_start <= rounded_end:
        return (rounded_start, rounded_end)
    return (rounded_end, rounded_start)


def _build_neighbors(vertices_by_id: dict[str, tuple[Point, ...]]) -> dict[str, tuple[str, ...]]:
    edge_owners: dict[EdgeKey, list[str]] = defaultdict(list)
    for cell_id, vertices in vertices_by_id.items():
        for index, start in enumerate(vertices):
            end = vertices[(index + 1) % len(vertices)]
            edge_owners[_canonicalize_edge(start, end)].append(cell_id)

    neighbors: dict[str, set[str]] = {cell_id: set() for cell_id in vertices_by_id}
    for owners in edge_owners.values():
        unique_owners = sorted(set(owners))
        if len(unique_owners) != 2:
            continue
        left, right = unique_owners
        neighbors[left].add(right)
        neighbors[right].add(left)

    return {
        cell_id: tuple(sorted(neighbor_ids))
        for cell_id, neighbor_ids in neighbors.items()
    }


def _compute_bounds(vertices_by_id: dict[str, tuple[Point, ...]]) -> tuple[int, int]:
    all_vertices = [vertex for vertices in vertices_by_id.values() for vertex in vertices]
    if not all_vertices:
        return (1, 1)

    xs = [point[0] for point in all_vertices]
    ys = [point[1] for point in all_vertices]
    width = max(1, math.ceil(max(xs) - min(xs)))
    height = max(1, math.ceil(max(ys) - min(ys)))
    return (width, height)


def build_dodecagonal_square_triangle_patch(patch_depth: int) -> AperiodicPatch:
    resolved_depth = _resolve_depth(patch_depth)
    threshold = _resolve_threshold(resolved_depth)

    selected_records = [
        record
        for record in _load_reference_records()
        if int(record["graph_distance"]) <= threshold
    ]

    cells_without_neighbors: list[PatchCell] = []
    vertices_by_id: dict[str, tuple[Point, ...]] = {}

    for record in selected_records:
        center = _to_point(record["center"])
        vertices = tuple(_to_point(vertex) for vertex in record["vertices"])
        cell_id = str(record["id"])
        vertices_by_id[cell_id] = vertices
        cells_without_neighbors.append(
            PatchCell(
                id=cell_id,
                kind=str(record["kind"]),
                center=center,
                vertices=vertices,
                neighbors=(),
                tile_family=str(record["tile_family"]) if record["tile_family"] is not None else None,
                orientation_token=(
                    str(record["orientation_token"])
                    if record["orientation_token"] is not None
                    else None
                ),
                chirality_token=(
                    str(record["chirality_token"])
                    if record["chirality_token"] is not None
                    else None
                ),
                decoration_tokens=None,
            )
        )

    neighbors_by_id = _build_neighbors(vertices_by_id)
    width, height = _compute_bounds(vertices_by_id)

    ordered_cells = tuple(
        PatchCell(
            id=cell["id"],
            kind=cell["kind"],
            center=cell["center"],
            vertices=cell["vertices"],
            neighbors=neighbors_by_id[cell["id"]],
            tile_family=cell["tile_family"],
            orientation_token=cell["orientation_token"],
            chirality_token=cell["chirality_token"],
            decoration_tokens=cell["decoration_tokens"],
        )
        for cell in sorted(cells_without_neighbors, key=lambda item: item["id"])
    )

    return AperiodicPatch(
        patch_depth=resolved_depth,
        width=width,
        height=height,
        cells=ordered_cells,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a dodecagonal square-triangle patch from the contract dataset."
    )
    parser.add_argument("patch_depth", type=int, help="Requested patch depth.")
    parser.add_argument(
        "--indent",
        type=int,
        default=2,
        help="JSON indentation level for printed output.",
    )
    args = parser.parse_args()

    patch = build_dodecagonal_square_triangle_patch(args.patch_depth)
    json.dump(patch, sys.stdout, indent=args.indent)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
