from __future__ import annotations

# Generated by tools/export_dodecagonal_square_triangle_contract_generator.py.
# Do not edit by hand; regenerate from the checked-in backend generator contract.

import json
import unittest
from pathlib import Path

from generator import build_dodecagonal_square_triangle_patch


BASE_DIR = Path(__file__).resolve().parent
EXPECTED_PATCHES_DIR = BASE_DIR / "expected-patches"


def _to_jsonable(value: object) -> object:
    return json.loads(json.dumps(value))


def _load_expected_patch(depth: int) -> dict[str, object]:
    patch_path = EXPECTED_PATCHES_DIR / f"patch-depth-{depth}.json"
    with patch_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


class BuildDodecagonalSquareTrianglePatchTests(unittest.TestCase):
    def assertPatchMatchesExpected(self, requested_depth: int, expected_depth: int) -> None:
        actual = _to_jsonable(build_dodecagonal_square_triangle_patch(requested_depth))
        expected = _load_expected_patch(expected_depth)
        if requested_depth >= 0:
            expected["patch_depth"] = requested_depth
        self.assertEqual(actual, expected)

    def test_expected_patches_match_for_depths_zero_through_four(self) -> None:
        for depth in range(5):
            with self.subTest(depth=depth):
                self.assertPatchMatchesExpected(depth, depth)

    def test_negative_depth_behaves_like_depth_zero(self) -> None:
        actual = _to_jsonable(build_dodecagonal_square_triangle_patch(-7))
        expected = _load_expected_patch(0)
        self.assertEqual(actual, expected)

    def test_depth_above_max_uses_depth_four_selection(self) -> None:
        requested_depth = 9
        actual = _to_jsonable(build_dodecagonal_square_triangle_patch(requested_depth))
        expected = _load_expected_patch(4)
        expected["patch_depth"] = requested_depth
        self.assertEqual(actual, expected)


if __name__ == "__main__":
    unittest.main()
