from __future__ import annotations

from backend.simulation.reference_verification.depth import (
    _depth_topology_expectation_failures,
    _expectation_failures,
    _metadata_failures,
)
from backend.simulation.reference_verification.fixtures import (
    _canonical_patch_fixture_failures,
    _canonical_patch_payload,
    _cell_local_reference_payload,
    _load_canonical_reference_fixtures,
    _load_local_reference_fixtures,
    _local_reference_fixture_failures,
)
from backend.simulation.reference_verification.observation import (
    _cells_bounds,
    _cells_bounds_aspect_ratio,
    _component_size_summary,
    _observe_reference_topology,
    _periodic_face_sample_size,
    _polygon_area,
    _polygon_area_frequencies_by_kind,
    _topology_adjacency_pairs,
    _topology_connectivity_stats,
    _topology_signature,
    _topology_signature_payload,
    observe_reference_patch,
)
from backend.simulation.reference_verification.periodic import (
    _canonicalize_vertex_configuration,
    _compile_periodic_face_id_pattern,
    _parse_periodic_face_cell_id,
    _periodic_face_descriptor_failures,
    _periodic_face_dual_candidate_failure,
    _periodic_face_dual_structure_failure,
    _periodic_face_interior_vertex_configuration_frequencies,
    _periodic_face_interior_vertex_configuration_occurrences,
    _periodic_face_interior_vertex_configurations,
    _periodic_face_translation_failures,
    _periodic_face_unique_polygon_side_counts,
    _periodic_face_vertex_valence_frequency_signature,
    _verify_periodic_face_id_roundtrip,
)
from backend.simulation.reference_verification.runner import (
    _builder_signal_failures,
    _pinwheel_exact_path_failures,
    _verify_spec,
    verify_all_reference_families,
    verify_reference_family,
)
from backend.simulation.reference_verification.types import (
    ReferenceCheckFailure,
    ReferencePatchObservation,
    ReferenceVerificationResult,
    VerificationStatus,
)

__all__ = [
    "ReferenceCheckFailure",
    "ReferencePatchObservation",
    "ReferenceVerificationResult",
    "VerificationStatus",
    "_builder_signal_failures",
    "_canonical_patch_fixture_failures",
    "_canonical_patch_payload",
    "_canonicalize_vertex_configuration",
    "_cell_local_reference_payload",
    "_cells_bounds",
    "_cells_bounds_aspect_ratio",
    "_compile_periodic_face_id_pattern",
    "_component_size_summary",
    "_depth_topology_expectation_failures",
    "_expectation_failures",
    "_load_canonical_reference_fixtures",
    "_load_local_reference_fixtures",
    "_local_reference_fixture_failures",
    "_metadata_failures",
    "_observe_reference_topology",
    "_parse_periodic_face_cell_id",
    "_periodic_face_descriptor_failures",
    "_periodic_face_dual_candidate_failure",
    "_periodic_face_dual_structure_failure",
    "_periodic_face_interior_vertex_configuration_frequencies",
    "_periodic_face_interior_vertex_configuration_occurrences",
    "_periodic_face_interior_vertex_configurations",
    "_periodic_face_sample_size",
    "_periodic_face_translation_failures",
    "_periodic_face_unique_polygon_side_counts",
    "_periodic_face_vertex_valence_frequency_signature",
    "_pinwheel_exact_path_failures",
    "_polygon_area",
    "_polygon_area_frequencies_by_kind",
    "_topology_adjacency_pairs",
    "_topology_connectivity_stats",
    "_topology_signature",
    "_topology_signature_payload",
    "_verify_periodic_face_id_roundtrip",
    "_verify_spec",
    "observe_reference_patch",
    "verify_all_reference_families",
    "verify_reference_family",
]
