from __future__ import annotations

import argparse
import sys
from pathlib import Path
from string import Template


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.simulation.aperiodic_dodecagonal_square_triangle import _PATCH_DISTANCE_THRESHOLDS
from backend.simulation.aperiodic_support import COORDINATE_PRECISION


DEFAULT_OUTPUT_DIR = ROOT / "docs" / "contracts" / "dodecagonal-square-triangle-generator"


def _format_thresholds_literal() -> str:
    lines = ["{"]
    for depth, threshold in sorted(_PATCH_DISTANCE_THRESHOLDS.items()):
        lines.append(f"    {depth}: {threshold},")
    lines.append("}")
    return "\n".join(lines)


def build_generated_generator_source() -> str:
    template = Template(
        """from __future__ import annotations

# Generated by tools/export_dodecagonal_square_triangle_contract_generator.py.
# Do not edit by hand; regenerate from the checked-in backend generator contract.

import argparse
import json
import math
import sys
from collections import defaultdict
from functools import lru_cache
from pathlib import Path
from typing import TypedDict


REFERENCE_PATCH_PATH = Path(__file__).resolve().parent / "reference-patch.json"
PATCH_DISTANCE_THRESHOLDS = $thresholds
EDGE_PRECISION = $edge_precision


class PatchCell(TypedDict):
    id: str
    kind: str
    center: tuple[float, float]
    vertices: tuple[tuple[float, float], ...]
    neighbors: tuple[str, ...]
    tile_family: str | None
    orientation_token: str | None
    chirality_token: str | None
    decoration_tokens: tuple[str, ...] | None


class AperiodicPatch(TypedDict):
    patch_depth: int
    width: int
    height: int
    cells: tuple[PatchCell, ...]


Point = tuple[float, float]
EdgeKey = tuple[Point, Point]


@lru_cache(maxsize=1)
def _load_reference_records() -> tuple[dict[str, object], ...]:
    with REFERENCE_PATCH_PATH.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    return tuple(payload["records"])


def _resolve_depth(patch_depth: int) -> int:
    return max(0, int(patch_depth))


def _resolve_threshold(resolved_depth: int) -> int:
    min_depth = min(PATCH_DISTANCE_THRESHOLDS)
    max_depth = max(PATCH_DISTANCE_THRESHOLDS)
    clamped_depth = min(max(resolved_depth, min_depth), max_depth)
    return PATCH_DISTANCE_THRESHOLDS[clamped_depth]


def _to_point(raw_point: list[float]) -> Point:
    return (float(raw_point[0]), float(raw_point[1]))


def _round_point(point: Point) -> Point:
    return (round(point[0], EDGE_PRECISION), round(point[1], EDGE_PRECISION))


def _canonicalize_edge(start: Point, end: Point) -> EdgeKey:
    rounded_start = _round_point(start)
    rounded_end = _round_point(end)
    if rounded_start <= rounded_end:
        return (rounded_start, rounded_end)
    return (rounded_end, rounded_start)


def _build_neighbors(vertices_by_id: dict[str, tuple[Point, ...]]) -> dict[str, tuple[str, ...]]:
    edge_owners: dict[EdgeKey, list[str]] = defaultdict(list)
    for cell_id, vertices in vertices_by_id.items():
        for index, start in enumerate(vertices):
            end = vertices[(index + 1) % len(vertices)]
            edge_owners[_canonicalize_edge(start, end)].append(cell_id)

    neighbors: dict[str, set[str]] = {cell_id: set() for cell_id in vertices_by_id}
    for owners in edge_owners.values():
        unique_owners = sorted(set(owners))
        if len(unique_owners) != 2:
            continue
        left, right = unique_owners
        neighbors[left].add(right)
        neighbors[right].add(left)

    return {
        cell_id: tuple(sorted(neighbor_ids))
        for cell_id, neighbor_ids in neighbors.items()
    }


def _compute_bounds(vertices_by_id: dict[str, tuple[Point, ...]]) -> tuple[int, int]:
    all_vertices = [vertex for vertices in vertices_by_id.values() for vertex in vertices]
    if not all_vertices:
        return (1, 1)

    xs = [point[0] for point in all_vertices]
    ys = [point[1] for point in all_vertices]
    width = max(1, math.ceil(max(xs) - min(xs)))
    height = max(1, math.ceil(max(ys) - min(ys)))
    return (width, height)


def build_dodecagonal_square_triangle_patch(patch_depth: int) -> AperiodicPatch:
    resolved_depth = _resolve_depth(patch_depth)
    threshold = _resolve_threshold(resolved_depth)

    selected_records = [
        record
        for record in _load_reference_records()
        if int(record["graph_distance"]) <= threshold
    ]

    cells_without_neighbors: list[PatchCell] = []
    vertices_by_id: dict[str, tuple[Point, ...]] = {}

    for record in selected_records:
        center = _to_point(record["center"])
        vertices = tuple(_to_point(vertex) for vertex in record["vertices"])
        cell_id = str(record["id"])
        vertices_by_id[cell_id] = vertices
        cells_without_neighbors.append(
            PatchCell(
                id=cell_id,
                kind=str(record["kind"]),
                center=center,
                vertices=vertices,
                neighbors=(),
                tile_family=str(record["tile_family"]) if record["tile_family"] is not None else None,
                orientation_token=(
                    str(record["orientation_token"])
                    if record["orientation_token"] is not None
                    else None
                ),
                chirality_token=(
                    str(record["chirality_token"])
                    if record["chirality_token"] is not None
                    else None
                ),
                decoration_tokens=None,
            )
        )

    neighbors_by_id = _build_neighbors(vertices_by_id)
    width, height = _compute_bounds(vertices_by_id)

    ordered_cells = tuple(
        PatchCell(
            id=cell["id"],
            kind=cell["kind"],
            center=cell["center"],
            vertices=cell["vertices"],
            neighbors=neighbors_by_id[cell["id"]],
            tile_family=cell["tile_family"],
            orientation_token=cell["orientation_token"],
            chirality_token=cell["chirality_token"],
            decoration_tokens=cell["decoration_tokens"],
        )
        for cell in sorted(cells_without_neighbors, key=lambda item: item["id"])
    )

    return AperiodicPatch(
        patch_depth=resolved_depth,
        width=width,
        height=height,
        cells=ordered_cells,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a dodecagonal square-triangle patch from the contract dataset."
    )
    parser.add_argument("patch_depth", type=int, help="Requested patch depth.")
    parser.add_argument(
        "--indent",
        type=int,
        default=2,
        help="JSON indentation level for printed output.",
    )
    args = parser.parse_args()

    patch = build_dodecagonal_square_triangle_patch(args.patch_depth)
    json.dump(patch, sys.stdout, indent=args.indent)
    sys.stdout.write("\\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""
    )
    return template.substitute(
        thresholds=_format_thresholds_literal(),
        edge_precision=str(COORDINATE_PRECISION),
    )


def build_generated_test_source() -> str:
    return """from __future__ import annotations

# Generated by tools/export_dodecagonal_square_triangle_contract_generator.py.
# Do not edit by hand; regenerate from the checked-in backend generator contract.

import json
import unittest
from pathlib import Path

from generator import build_dodecagonal_square_triangle_patch


BASE_DIR = Path(__file__).resolve().parent
EXPECTED_PATCHES_DIR = BASE_DIR / "expected-patches"


def _to_jsonable(value: object) -> object:
    return json.loads(json.dumps(value))


def _load_expected_patch(depth: int) -> dict[str, object]:
    patch_path = EXPECTED_PATCHES_DIR / f"patch-depth-{depth}.json"
    with patch_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


class BuildDodecagonalSquareTrianglePatchTests(unittest.TestCase):
    def assertPatchMatchesExpected(self, requested_depth: int, expected_depth: int) -> None:
        actual = _to_jsonable(build_dodecagonal_square_triangle_patch(requested_depth))
        expected = _load_expected_patch(expected_depth)
        if requested_depth >= 0:
            expected["patch_depth"] = requested_depth
        self.assertEqual(actual, expected)

    def test_expected_patches_match_for_depths_zero_through_four(self) -> None:
        for depth in range(5):
            with self.subTest(depth=depth):
                self.assertPatchMatchesExpected(depth, depth)

    def test_negative_depth_behaves_like_depth_zero(self) -> None:
        actual = _to_jsonable(build_dodecagonal_square_triangle_patch(-7))
        expected = _load_expected_patch(0)
        self.assertEqual(actual, expected)

    def test_depth_above_max_uses_depth_four_selection(self) -> None:
        requested_depth = 9
        actual = _to_jsonable(build_dodecagonal_square_triangle_patch(requested_depth))
        expected = _load_expected_patch(4)
        expected["patch_depth"] = requested_depth
        self.assertEqual(actual, expected)


if __name__ == "__main__":
    unittest.main()
"""


def generated_sources() -> dict[str, str]:
    return {
        "generator.py": build_generated_generator_source(),
        "test_generator.py": build_generated_test_source(),
    }


def drift_lines(output_dir: Path = DEFAULT_OUTPUT_DIR) -> list[str]:
    drift: list[str] = []
    for name, generated_text in generated_sources().items():
        target_path = output_dir / name
        if not target_path.exists():
            drift.append(name)
            continue
        if target_path.read_text(encoding="utf-8") != generated_text:
            drift.append(name)
    return drift


def write_generated_sources(output_dir: Path = DEFAULT_OUTPUT_DIR) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, generated_text in generated_sources().items():
        (output_dir / name).write_text(generated_text, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate the standalone dodecagonal square-triangle contract generator files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory that will receive generator.py and test_generator.py.",
    )
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    output_dir = Path(args.output_dir).resolve()
    if bool(args.check):
        drift = drift_lines(output_dir)
        if drift:
            print("Dodecagonal square-triangle contract generator drift detected:")
            for name in drift:
                print(f"  {name}")
            return 1
        print("Dodecagonal square-triangle contract generator files are up to date.")
        return 0

    write_generated_sources(output_dir)
    print(f"Wrote standalone contract generator files to {output_dir}")
    for name in sorted(generated_sources()):
        print(f"  {output_dir / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
