from __future__ import annotations

import argparse
import ast
import gzip
import json
import math
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from backend.simulation.topology_family_manifest import TOPOLOGY_FAMILY_MANIFEST
from tools._common import ROOT_DIR
from tools.add_periodic_tiling import (
    InstallMetadata,
    PlannedWrite,
    build_install_plan,
    check_install,
)
from tools.sketch_tiling import load_sketch

_DESCRIPTOR_DIR = Path("backend/simulation/data/periodic_face_patterns")
_REFERENCE_DIR = Path("backend/simulation/reference_specs/periodic")
_SKETCH_DIR = Path("tools/sketch_examples")
_PALETTE_PATH = Path("frontend/canvas/family-dead-palette-manifest.json")
_BOOTSTRAP_PATH = Path("frontend/test-fixtures/bootstrap-data.json")
_BUDGET_PATH = Path("tools/standalone_bundle_budget.json")
_SHARED_CATALOG_PATHS = frozenset(
    {
        Path("backend/simulation/topology_family_manifest.py"),
        _PALETTE_PATH,
        Path("frontend/controls/tiling-preview-data.ts"),
    }
)
_GENERATED_REFERENCE_MARKER = "Generated by tools/sketch_tiling.py"


@dataclass(frozen=True)
class CatalogSource:
    geometry: str
    sketch_path: Path
    source_url: str
    metadata: InstallMetadata


@dataclass(frozen=True)
class CatalogInventory:
    descriptor_geometries: frozenset[str]
    reference_geometries: frozenset[str]
    sources: tuple[CatalogSource, ...]


def _literal_string(node: ast.AST | None) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


def _reference_records(root: Path) -> tuple[set[str], dict[str, str]]:
    geometries: set[str] = set()
    generated_sources: dict[str, str] = {}
    for path in sorted((root / _REFERENCE_DIR).glob("*.py")):
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            function_name = node.func.id if isinstance(node.func, ast.Name) else None
            if function_name != "ReferenceFamilySpec":
                continue
            keywords = {keyword.arg: keyword.value for keyword in node.keywords if keyword.arg}
            geometry = _literal_string(keywords.get("geometry"))
            if geometry is None:
                continue
            geometries.add(geometry)
            if _GENERATED_REFERENCE_MARKER not in source:
                continue
            urls = keywords.get("source_urls")
            if isinstance(urls, (ast.Tuple, ast.List)) and urls.elts:
                source_url = _literal_string(urls.elts[0])
                if source_url:
                    generated_sources[geometry] = source_url
    return geometries, generated_sources


def _sketch_records(root: Path) -> dict[str, Path]:
    records: dict[str, Path] = {}
    for path in sorted((root / _SKETCH_DIR).glob("*.py")):
        geometry = load_sketch(path).geometry
        if geometry in records:
            raise ValueError(f"Duplicate periodic sketches for '{geometry}'.")
        records[geometry] = path
    return records


def discover_catalog_sources(root: Path = ROOT_DIR) -> CatalogInventory:
    descriptors = frozenset(path.stem for path in (root / _DESCRIPTOR_DIR).glob("*.json"))
    reference_geometries, generated_sources = _reference_records(root)
    missing_references = sorted(descriptors - reference_geometries)
    if missing_references:
        raise ValueError(
            "Periodic descriptors missing reference specs: " + ", ".join(missing_references)
        )

    sketches = _sketch_records(root)
    palette_payload = json.loads((root / _PALETTE_PATH).read_text(encoding="utf-8"))
    palette_tokens = {
        str(family["geometry"]): {
            str(variant["selector"]["kind"]): str(variant["color"]["token"])
            for variant in family.get("variants", [])
            if isinstance(variant, dict)
            and "kind" in variant.get("selector", {})
            and isinstance(variant.get("color"), dict)
        }
        for family in palette_payload.get("families", [])
        if isinstance(family, dict) and "geometry" in family
    }

    sources: list[CatalogSource] = []
    for geometry, source_url in sorted(generated_sources.items()):
        sketch_path = sketches.get(geometry)
        manifest_entry = TOPOLOGY_FAMILY_MANIFEST.get(geometry)
        if sketch_path is None:
            raise ValueError(f"Generated reference spec '{geometry}' has no permanent sketch.")
        if manifest_entry is None:
            raise ValueError(
                f"Generated periodic tiling '{geometry}' has no manifest metadata; "
                "repair it with `tilings add-periodic --reconcile` first."
            )
        tokens = palette_tokens.get(geometry)
        if not tokens:
            raise ValueError(f"Generated periodic tiling '{geometry}' has no palette metadata.")
        sizing = manifest_entry.sizing_policy
        sources.append(
            CatalogSource(
                geometry=geometry,
                sketch_path=sketch_path,
                source_url=source_url,
                metadata=InstallMetadata(
                    source_url=source_url,
                    picker_order=manifest_entry.picker_order,
                    default_cell_size=sizing.default,
                    min_cell_size=sizing.minimum,
                    max_cell_size=sizing.maximum,
                    default_rule=manifest_entry.variants[0].default_rule,
                    palette_tokens=tokens,
                ),
            )
        )
    return CatalogInventory(descriptors, frozenset(reference_geometries), tuple(sources))


def refresh_bootstrap_budget_source(source: str, bootstrap_data: bytes) -> str:
    payload = json.loads(source)
    category = next(item for item in payload["categories"] if item.get("name") == "bootstrap-data")
    actuals = {
        "raw": len(bootstrap_data),
        "gzip": len(gzip.compress(bootstrap_data, mtime=0)),
    }
    increments = {"raw": 5_000, "gzip": 1_000}
    for metric, actual in actuals.items():
        current = int(category[metric])
        if actual * 100 >= current * 85:
            target = math.ceil((actual * 1.15) / increments[metric]) * increments[metric]
            category[metric] = max(current, target)
    pattern = re.compile(
        r'("name"\s*:\s*"bootstrap-data"[^\n]*?"raw"\s*:\s*)\d+'
        r'([^\n]*?"gzip"\s*:\s*)\d+'
    )
    replacement = (
        rf"\g<1>{int(category['raw'])}"
        rf"\g<2>{int(category['gzip'])}"
    )
    refreshed, count = pattern.subn(replacement, source, count=1)
    if count != 1:
        raise ValueError("Bootstrap-data budget entry must remain on one line.")
    return refreshed


def _run(command: list[str], *, root: Path) -> None:
    result = subprocess.run(command, cwd=root, check=False)
    if result.returncode:
        raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(command)}")


def _write_with_backup(
    write: PlannedWrite,
    backups: dict[Path, bytes | None],
) -> None:
    if write.path not in backups:
        backups[write.path] = write.path.read_bytes() if write.path.exists() else None
    write.path.parent.mkdir(parents=True, exist_ok=True)
    write.path.write_text(write.content, encoding="utf-8")


def regenerate_catalog(root: Path = ROOT_DIR) -> tuple[Path, ...]:
    inventory = discover_catalog_sources(root)
    backups: dict[Path, bytes | None] = {}
    written: set[Path] = set()
    bootstrap_path = root / _BOOTSTRAP_PATH
    budget_path = root / _BUDGET_PATH
    try:
        for source in inventory.sources:
            writes = build_install_plan(
                source.sketch_path,
                source.metadata,
                root=root,
                patch_size=4,
                reconcile=True,
            )
            for write in writes:
                if write.path.relative_to(root) not in _SHARED_CATALOG_PATHS:
                    continue
                _write_with_backup(write, backups)
                written.add(write.path)

        for path in (bootstrap_path, budget_path):
            if path not in backups:
                backups[path] = path.read_bytes() if path.exists() else None
        _run(
            [sys.executable, "-m", "tools", "bootstrap", "export", str(_BOOTSTRAP_PATH)],
            root=root,
        )
        budget_source = refresh_bootstrap_budget_source(
            budget_path.read_text(encoding="utf-8"),
            bootstrap_path.read_bytes(),
        )
        budget_path.write_text(budget_source, encoding="utf-8")
        written.update((bootstrap_path, budget_path))

        python_paths = sorted(str(path) for path in written if path.suffix == ".py")
        if python_paths:
            _run([sys.executable, "-m", "ruff", "format", *python_paths], root=root)
            _run([sys.executable, "-m", "ruff", "check", *python_paths], root=root)
        _run(
            [
                "npm",
                "exec",
                "prettier",
                "--",
                "--write",
                "frontend/controls/tiling-preview-data.ts",
            ],
            root=root,
        )
        _run([sys.executable, "-m", "tools", "tilings", "validate"], root=root)
        _run([sys.executable, "-m", "tools", "tilings", "verify"], root=root)
    except Exception:
        for path, content in backups.items():
            if content is None:
                path.unlink(missing_ok=True)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
        raise
    return tuple(sorted(written))


def check_catalog(root: Path = ROOT_DIR) -> tuple[str, ...]:
    inventory = discover_catalog_sources(root)
    problems: list[str] = []
    for source in inventory.sources:
        problems.extend(
            f"{source.geometry}: {problem}"
            for problem in check_install(source.sketch_path, root=root, patch_size=4)
        )
    expected_budget = refresh_bootstrap_budget_source(
        (root / _BUDGET_PATH).read_text(encoding="utf-8"),
        (root / _BOOTSTRAP_PATH).read_bytes(),
    )
    if expected_budget != (root / _BUDGET_PATH).read_text(encoding="utf-8"):
        problems.append("standalone bootstrap budget lacks catalog headroom")
    return tuple(problems)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Deterministically reconcile scaffold-generated periodic catalog surfaces."
    )
    parser.add_argument("--check", action="store_true", help="Report drift without writing files.")
    parser.add_argument("--dry-run", action="store_true", help="List managed tilings and exit.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        inventory = discover_catalog_sources(ROOT_DIR)
        if args.dry_run:
            for source in inventory.sources:
                print(source.geometry)
            return 0
        if args.check:
            problems = check_catalog(ROOT_DIR)
            if problems:
                for problem in problems:
                    print(f"FAIL: {problem}", file=sys.stderr)
                return 1
            print(f"Periodic catalog is current ({len(inventory.sources)} managed tilings).")
            return 0
        written = regenerate_catalog(ROOT_DIR)
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError, SyntaxError) as error:
        print(str(error), file=sys.stderr)
        return 1
    print(
        f"Regenerated periodic catalog for {len(inventory.sources)} managed tilings "
        f"across {len(written)} files."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
