export const COMPACT_RENDER_MAX_CELL_SIZE = 4;
export const STANDARD_RENDER_MAX_CELL_SIZE = 8;

export const COMPACT_POLYGON_STROKE_WIDTH = 1;
export const STANDARD_POLYGON_STROKE_WIDTH = 1.25;
export const SHIELD_FILL_BRIDGE_STROKE_WIDTH = 2.5;
export const HOVER_MIN_STROKE_WIDTH = 1.5;
export const SELECTION_MIN_STROKE_WIDTH = 2.5;
export const GESTURE_OUTLINE_MIN_STROKE_WIDTH = 2.25;

export const DARK_HOVER_PALETTE_LUMINANCE_THRESHOLD = 0.6;
export const DARK_HOVER_TINT_ALPHA = 0.18;
export const DARK_HOVER_STROKE_ALPHA = 0.9;
export const LIGHT_SELECTION_TINT_ALPHA = 0.16;
export const DARK_SELECTION_TINT_ALPHA = 0.18;
